volumes:
  postgres_data:
    driver: local

services:
  ruitunion_feedbackbot:
    container_name: RuItUnion.FeedbackBot
    image: ${DOCKER_REGISTRY-}ruitunionfeedbackbot
    restart: always
    build:
      context: .
      dockerfile: RuItUnion.FeedbackBot/Dockerfile
    healthcheck:
      test: curl -f http://localhost/health || exit 1 
      interval: 5s
      timeout: 10s
    environment:
      - ASPNETCORE_HTTP_PORTS=8080


  ruitunion_feedbackbot_database:
    container_name: RuItUnion.FeedbackBot.Database
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 5s
      timeout: 10s
    environment:
      POSTGRES_DB: feedback_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
